### PR TITLE
Move the QAPage Question into mainEntity

### PR DESCRIPTION
**Pull request by notriddle**
Fixes
https://meta.discourse.org/t/support-schema-org-qapage-and-google-rich-results/33813/14?u=notriddle

### CODE REVIEW

**Comment by notriddle** [comment]
Weird. It looks like it's eslint that failed, but I never modified any javascript files at all.

**Comment by SamSaffron** [comment]
@notriddle we really need 1 integration test here that confirms the behavior is good. I am happy to assign this to another team member if you feel its a bit too hard to get a test going. Technically all you need to do is an integration test that creates a topic and then does a `get "/topic/slug/id"` and look at what you get.

**Comment by notriddle** [comment]
Yeah, probably do assign the integration test to someone else.

**Comment by SamSaffron** [comment]
@vinothkannans can you finalize this PR (add a test and merge when ready) ?

**Comment by SidVal** [comment]
Any update about this @vinothkannans  ? 🙏

**Comment by vinothkannans** [comment]
thanks for the PR ❤️

**Pull request merged**
