### PR TITLE
Change parameters from true/false to solved/unsolved.

### PR DESCRIPTION
**Pull request by davidtaylorhq**
Sorry @SamSaffron, got another one for you. 

Using 'true'/'false' in the query variables wasn't working, because Ember interpreted the default as False (wheras we need 3 states: solved, unsolved & all). I've changed the strings to 'solved'/'unsolved' to work around that issue.

https://discuss.emberjs.com/t/boolean-query-params/4301

### CODE REVIEW

**Comment by SamSaffron** [comment]
grrr the "solved=solved" sure is ugly... maybe "solved=all" and
"solved=none" ?

**Comment by davidtaylorhq** [comment]
How about `solved=yes` and `solved=no`? And then the lack of a value is the default - that way it's the same as `status=open` `status=closed` and `status=archived`

**Comment by SamSaffron** [comment]
yes, no is fine as well imo

**Comment by davidtaylorhq** [comment]
Changed to yes/no

**Comment by SamSaffron** [comment]
OK let's try this out

**Pull request merged**
