### PR TITLE
[WIP] Send email notification for long standing topic

### PR DESCRIPTION
**Pull request by bekicot**

### CODE REVIEW

**Comment by erlend-sh** [comment]
Relevant topic on Meta:

https://meta.discourse.org/t/a-feature-for-the-accepted-answer-plugin-send-a-letter-to-a-questions-author-with-request-to-choose-and-mark-a-solution/36069?u=erlend_sh

**Comment by tgxworld** [comment]
Is this still a WIP?

**Comment by jexp** [comment]
ping?

**Comment by tgxworld** [comment]
Closing this as stale. Let me know if you're keen on picking this up again @bekicot  :+1:

**Pull request closed without merging**
