### PR TITLE
Quote accepted answer at top

### PR DESCRIPTION
**Pull request by davidtaylorhq**
https://meta.discourse.org/t/option-to-move-accepted-answer-to-the-top/58386/16?u=david_taylor

Makes use of PostCooked to build the quote UI the same way as in the rest of Discourse.

### CODE REVIEW

**Comment by SamSaffron** [comment]
might as well remove "acceptedAnswerHtml" if we are no longer using it :)

**Comment by davidtaylorhq** [comment]
It's still being used - to fill in the title at the top of the quote. E.g.  `Solved by David in post #3`

**Comment by SamSaffron** [comment]
K well lets see how this goes! thanks. I still want the excerpt though but we can get to it later by amending the serializer

**Comment by davidtaylorhq** [comment]
Thanks :)

I've got the excerpt bit working by adding to the serialiser, but removed it following discussions on meta. We can discuss further on there.

**Pull request merged**
